name: debug

on:
  push:
    branches:
      - gobuild
  pull_request:
    branches:
      - gobuild

jobs:

  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Cache Data
      uses: actions/cache@v2
      with:
        path: ~/.actions-cache
        key: caches
        restore-keys: |
          caches

    - name: Setup Android Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "./gradlew assembleDebug"
